
services:
  backend:
    build: ./backend
    container_name: whatsapp-ai-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/.wwebjs_auth:/app/.wwebjs_auth
    restart: always
    networks:
      - ai-network
    depends_on:
      - ngrok
  
  ngrok:
    image: ngrok/ngrok:latest
    container_name: whatsapp-ai-ngrok
    command: http backend:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    ports:
      - "4040:4040"
    networks:
      - ai-network
    restart: unless-stopped

networks:
  ai-network:
    driver: bridge